name: UI Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests against'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production
          - development
      user_type:
        description: 'Type of user to run tests with'
        required: true
        default: 'standard'
        type: choice
        options:
          - standard
          - locked
          - problem
          - performance

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      ENV: ${{ github.event.inputs.environment || 'staging' }}
      BASE_URL: ${{ github.event.inputs.environment == 'production' && 'https://www.saucedemo.com' || github.event.inputs.environment == 'staging' && 'https://staging.saucedemo.com' || 'https://dev.saucedemo.com' }}
      USER_TYPE: ${{ github.event.inputs.user_type || 'standard' }}
      STANDARD_USER: ${{ secrets.STANDARD_USER }}
      LOCKED_USER: ${{ secrets.LOCKED_USER }}
      PROBLEM_USER: ${{ secrets.PROBLEM_USER }}
      PERFORMANCE_USER: ${{ secrets.PERFORMANCE_USER }}
      PASSWORD: ${{ secrets.PASSWORD }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run UI Tests
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30 